### ISSUE TITLE
Effect issues

### ISSUE THREAD

**Issue by Kody420** [Kody420/ModPad#2]
## Effect 3 (breathing)
- sometimes leds are blinking really fast
- problem is coused by changing the brightness with other effects. The delta is than in the wrong cycle and insted of cycling between
		 min and max its overflowing and hitting min or max from "other side"
- is fixed by reseting the device or just switching few times between effects
## Effect 1 (off)
- is not really off but rather minimum brightness (but is kinda nice bacouse I can tell if it's in bootloader)

**Comment by M4rc311o** [comment]
What about making the Modpad flash LEDs in the bootloader to indicate that it is in some kind of a programming mode and really turn it off in *Off* mode? In that way, you can still tell apart the bootloader from normal operation but off is off.
